# Generated by Django 3.2.3 on 2021-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign_up',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='sign_up',
            name='Retype_password',
            field=models.CharField(db_column='اعد ادخال كلمة السر', max_length=50, null=True, verbose_name='اعد ادخال كلمة السر'),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='User',
            field=models.CharField(db_column='اسم المستخدم', max_length=50, null=True, unique=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(db_column='البريد الاكتروني', max_length=100, null=True, unique=True, verbose_name='البريد الاكتروني'),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='password',
            field=models.CharField(db_column='كلمة السر', max_length=50, null=True, verbose_name='كلمة السر'),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='fullname',
            field=models.CharField(db_column='الاسم كامل', max_length=150, null=True, verbose_name='الاسم كامل'),
        ),
        migrations.AlterModelTable(
            name='sign_up',
            table='مستخدمين',
        ),
    ]
