# Generated by Django 3.2.3 on 2021-07-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210730_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign_up',
            options={},
        ),
    ]
