# Generated by Django 3.2.3 on 2021-07-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_sign_up_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign_up',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='User',
            field=models.CharField(db_column='اسم المستخدم', max_length=70, null=True, unique=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(db_column='البريد الاكتروني', max_length=254, null=True, unique=True, verbose_name='البريد الاكتروني'),
        ),
    ]
