# Generated by Django 3.2.3 on 2021-07-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210730_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_Up',
        ),
    ]
