# Generated by Django 3.2.3 on 2021-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0005_delete_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_column='الاسم كامل', max_length=150, null=True, verbose_name='الاسم كامل')),
                ('User', models.CharField(db_column='اسم المستخدم', max_length=70, null=True, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(db_column='البريد الاكتروني', max_length=254, null=True, unique=True, verbose_name='البريد الاكتروني')),
                ('password', models.CharField(db_column='كلمة السر', max_length=50, null=True, verbose_name='كلمة السر')),
                ('Retype_password', models.CharField(db_column='اعد ادخال كلمة السر', max_length=50, null=True, verbose_name='اعد ادخال كلمة السر')),
            ],
            options={
                'db_table': 'مستخدمين',
                'ordering': ['id'],
            },
        ),
    ]
